### ISSUE TITLE
Qt platform plugin error when running main.py

### ISSUE THREAD

**Issue by dieumerci7** [stupidcucumber/SimpleCOCO#2]
I am running _main_ with arguments suggested in _readme_:
`python main.py --root example/inputs --output output`
An error occurs:
`qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/app/.venv/lib/python3.10/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`
The error is usually related to the presence of PyQt files (PyQt5, PyQt5_sip-12.11.0-py3.10-linux-x86_64.egg, PyQt5_sip.pth) in the following path: `lib/python3.10/site-packages/`, but I don't have any.
The only solution that worked for me was to uninstall opencv-python (`pip uninstall opencv-python`) and install opencv-python-headless (`pip install opencv-python-headless`) instead.
Unfortunately, opencv-python-headless does not contain the imshow() function, which causes the next error:
`cv2.error: OpenCV(4.9.0) /io/opencv/modules/highgui/src/window.cpp:1272: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'`
For this problem, the web suggests to uninstall opencv-python-headless and install opencv-python instead. Unsurprisingly, doing that reinstates the initial error.

**Comment by stupidcucumber** [comment]
First, update repository:
```
git pull
```
I added opencv-python-contrib to the dependencies.

Looks like you are not using virtual environment and therefore I strongly suggest install it using [venv](https://docs.python.org/3/library/venv.html) or [conda](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment). Therefore any further changes to the packages will not break down your whole system.

When environment had been installed try to use command listed in the README.md:
```
python -m pip install -e requirements.txt
```

If the problem persists try to downgrade version of the opencv-python and opencv-python-contrib. Let me know if something has changed!

**Comment by dieumerci7** [comment]
Thank you for the answer!
In fact, I did use venv. The issue was in that I was running the code on a docker image without graphical environment. Now I tried to run the repo locally, and the problem is no more there.

**Comment by stupidcucumber** [comment]
Cool :)
